on:
  push:
    branches:
      - main   # Passe den Branch nach Bedarf an

permissions:
  contents: read
  deployments: write   # Erforderlich, damit cloudflare/pages-action GitHub Deployments erstellt :contentReference[oaicite:5]{index=5}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'   # oder deine gewünschte Version :contentReference[oaicite:6]{index=6}

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1      # Oder: cloudflare/wrangler-action@2 :contentReference[oaicite:7]{index=7}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: paperpresets             # Dein Pages-Projektname :contentReference[oaicite:8]{index=8}
          directory: target                     # Verzeichnis mit den statischen Artefakten :contentReference[oaicite:9]{index=9}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}  # Optional für Deployments :contentReference[oaicite:10]{index=10}
