name: Publish Maven Artifacts & Javadoc

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the main branch with full history
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Install JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3) Build and publish plugin artifacts
      - name: Build and Deploy to Local Repo
        run: mvn clean deploy -DskipTests

      # 4) Deploy Maven repo to Cloudflare Pages
      - name: Deploy Maven Repo to repo.tsgscraft.com
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: repo-tsgscraft
          directory: target/repo
          branch: main

      # 5) Generate Javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      # 6) Prepare versioned docs directory
      - name: Prepare versioned Javadoc folder
        run: |
          mkdir -p docs/${VERSION}
          cp -r target/site/apidocs/* docs/${VERSION}/

      # 7) Checkout gh-pages branch for docs
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          path: gh-pages
          repository: ${{ github.repository }}
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 8) Copy versioned docs into gh-pages
      - name: Copy versioned docs to gh-pages
        run: |
          cp -r docs/${VERSION} gh-pages/${VERSION}

      # 9) Commit & push updates to gh-pages
      - name: Commit and Push gh-pages updates
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${VERSION}
          git commit -m "Add Javadoc for ${{ env.VERSION }}"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
