name: Publish Maven Artifacts & Javadoc

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.ref_name }} # z. B. 1.1.2-dev4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and Deploy to Local Repo
        run: mvn clean deploy -DskipTests

      - name: Deploy Maven Repo to repo.tsgscraft.com
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: repo-tsgscraft
          directory: target/repo
          branch: main

      # 📦 Javadoc entpacken und in versionsspezifischen Ordner legen
      - name: Prepare versioned javadoc folder
        run: |
          mkdir -p docs/$VERSION
          unzip target/*-javadoc.jar -d docs/$VERSION

      # 📤 Vorherige Versionen beibehalten (gh-pages oder Pages-Projekt mit persistierendem Branch)
      - name: Checkout existing docs
        uses: actions/checkout@v4
        with:
          ref: main
          repository: tsgscraft/ppdocs
          path: all-docs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy current version into all-docs
        run: |
          mkdir -p all-docs/$VERSION
          cp -r docs/$VERSION/* all-docs/$VERSION/

      - name: Deploy Javadoc to ppdocs.tsgscraft.com
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ppdocs-tsgscraft
          directory: all-docs
          branch: main
