name: Publish Maven Artifacts & Javadoc

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) JDK 21 installieren
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 2) Maven Build & Deploy in target/repo
      - name: Build and Deploy to Local Repo
        run: mvn clean deploy -DskipTests
      # → Jetzt kompiliert Javac mit Release 21 ohne Fehler :contentReference[oaicite:4]{index=4}

      # 3) Deploy das Maven-Repo auf repo.tsgscraft.com
      - name: Deploy Maven Repo to repo.tsgscraft.com
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: repo-tsgscraft
          directory: target/repo

      # 4) Javadoc entpacken & deployen
      - name: Unpack Javadoc
        run: |
          mkdir docs
          unzip target/*.javadoc.jar -d docs
      - name: Deploy Javadoc to ppdocs.tsgscraft.com
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ppdocs-tsgscraft
          directory: docs
